# All values in this document are the ENVIRONMENT variable names that can override the defaults
# from `default.yaml`
---
ecosystem:
  store: ECOSYSTEM_STORE

queue:
  # redis or redisCluster(beta)
  connectionType: REDIS_TYPE
  redisConnection:
    host: REDIS_HOST
    port: REDIS_PORT
    options:
      password: REDIS_PASSWORD
      tls: REDIS_TLS_ENABLED
    database: REDIS_DB_NUMBER
  redisClusterConnection:
    hosts:
      __name: REDIS_CLUSTER_HOSTS
      __format: json
    options:
      password: REDIS_PASSWORD
      tls: REDIS_TLS_ENABLED
    slotsRefreshTimeout: REDIS_CLUSTER_SLOTS_REFRESH_TIMEOUT
  prefix: REDIS_QUEUE_PREFIX

unzip-service:
  # https://github.com/taskrabbit/node-resque#multiworker-options
  # minimum number of workers to spawn
  minTaskProcessors: WORKER_MIN_TASK_PROCESSORS
  # maximum number of workers to spawn
  maxTaskProcessors: WORKER_MAX_TASK_PROCESSORS
  # how often to check if the event loop is blocked (ms)
  checkTimeout: WORKER_CHECK_TIMEOUT
  # how long the event loop has to be delayed before considering it blocked (ms)
  maxEventLoopDelay: WORKER_MAX_EVENT_LOOP_DELAY
  # number of parallel executions for asynchronous upload of unzipped files to store
  parallelUploadLimit: WORKER_PARALLEL_UPLOAD_LIMIT

httpd:
  # Port to listen on
  port: PORT
  # Host to listen on (set to 0.0.0.0 to accept all connections)
  host: HOST
  # Externally routable URI (usually your load balancer or CNAME)
  uri: URI
